apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - vault-access.yaml
  - postgresql.yaml
  - deployment.yaml
  - certificate.yaml
  - ingressroute.yaml
  - backup.yaml
  - db-sync.yaml
  - maintenance.yaml
  - middlewares.yaml
