apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: website
  namespace: theater-website
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sommertheater-altrossthal.de`) || Host(`www.sommertheater-altrossthal.de`)
      kind: Rule
      services:
        - name: website
          port: 3000
  tls:
    certResolver: cloudflare
---
# HTTP → HTTPS redirect
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: website-http
  namespace: theater-website
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`sommertheater-altrossthal.de`) || Host(`www.sommertheater-altrossthal.de`)
      kind: Rule
      middlewares:
        - name: redirect-https
      services:
        - name: website
          port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: theater-website
spec:
  redirectScheme:
    scheme: https
    permanent: true
