apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-failover
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Schlossparktheater-Altrossthal/k8s-infrastructure
    targetRevision: HEAD
    path: infrastructure/cloudflare-failover
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
