apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailu
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://mailu.github.io/helm-charts/
      chart: mailu
      targetRevision: 2.7.1
      helm:
        releaseName: mailu
        valueFiles:
          - $values/infrastructure/mailu/helm-values.yaml
    - repoURL: https://github.com/Schlossparktheater-Altrossthal/k8s-infrastructure
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Schlossparktheater-Altrossthal/k8s-infrastructure
      targetRevision: HEAD
      path: infrastructure/mailu
  destination:
    server: https://kubernetes.default.svc
    namespace: mailu
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      namespace: mailu
      name: mailu-api
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      namespace: mailu
      name: mailu-initial-account
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      namespace: mailu
      name: mailu-roundcube
      jsonPointers:
        - /data
    - group: apps
      kind: StatefulSet
      namespace: mailu
      name: mailu-clamav
      jsonPointers:
        - /spec/volumeClaimTemplates
