apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: theater-vaultwarden
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Schlossparktheater-Altrossthal/k8s-infrastructure
    targetRevision: HEAD
    path: applications/vaultwarden
  destination:
    server: https://kubernetes.default.svc
    namespace: theater-vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
