apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: theater
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Schlossparktheater Altrossthal
  sourceRepos:
    - 'https://github.com/Schlossparktheater-Altrossthal/k8s-infrastructure'
    - 'https://github.com/Schlossparktheater-Altrossthal/Website'
  destinations:
    - namespace: theater-website
      server: https://kubernetes.default.svc
    - namespace: theater-website-staging
      server: https://kubernetes.default.svc
    - namespace: theater-vaultwarden
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
