apiVersion: apps/v1
kind: Deployment
metadata:
  name: theater-vaultwarden
  namespace: theater-vaultwarden
  labels:
    app: theater-vaultwarden
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: theater-vaultwarden
  template:
    metadata:
      labels:
        app: theater-vaultwarden
    spec:
      nodeSelector:
        sommertheater: "true"
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.36.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - secretRef:
                name: theater-vaultwarden-config
          readinessProbe:
            httpGet:
              path: /alive
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /alive
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: theater-vaultwarden-data
