apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: theater-vaultwarden-config
  namespace: theater-vaultwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: theater-vaultwarden-vault
  target:
    name: theater-vaultwarden-config
    creationPolicy: Owner
  data:
    - secretKey: DOMAIN
      remoteRef:
        key: apps/theater-vaultwarden
        property: DOMAIN
    - secretKey: SIGNUPS_ALLOWED
      remoteRef:
        key: apps/theater-vaultwarden
        property: SIGNUPS_ALLOWED
    - secretKey: INVITATIONS_ALLOWED
      remoteRef:
        key: apps/theater-vaultwarden
        property: INVITATIONS_ALLOWED
    - secretKey: SENDS_ALLOWED
      remoteRef:
        key: apps/theater-vaultwarden
        property: SENDS_ALLOWED
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: apps/theater-vaultwarden
        property: ADMIN_TOKEN
