apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: theater-vaultwarden-config
  namespace: theater-vaultwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: theater-vaultwarden-vault
  target:
    name: theater-vaultwarden-config
    creationPolicy: Owner
  data:
    - secretKey: DOMAIN
      remoteRef:
        key: apps/theater-vaultwarden
        property: DOMAIN
    - secretKey: SIGNUPS_ALLOWED
      remoteRef:
        key: apps/theater-vaultwarden
        property: SIGNUPS_ALLOWED
    - secretKey: INVITATIONS_ALLOWED
      remoteRef:
        key: apps/theater-vaultwarden
        property: INVITATIONS_ALLOWED
    - secretKey: SENDS_ALLOWED
      remoteRef:
        key: apps/theater-vaultwarden
        property: SENDS_ALLOWED
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: apps/theater-vaultwarden
        property: ADMIN_TOKEN
    - secretKey: SIGNUPS_VERIFY
      remoteRef:
        key: apps/theater-vaultwarden
        property: SIGNUPS_VERIFY
    - secretKey: EMERGENCY_ACCESS_ALLOWED
      remoteRef:
        key: apps/theater-vaultwarden
        property: EMERGENCY_ACCESS_ALLOWED
    - secretKey: IP_HEADER
      remoteRef:
        key: apps/theater-vaultwarden
        property: IP_HEADER
    - secretKey: SMTP_HOST
      remoteRef:
        key: apps/theater-vaultwarden
        property: SMTP_HOST
    - secretKey: SMTP_SECURITY
      remoteRef:
        key: apps/theater-vaultwarden
        property: SMTP_SECURITY
    - secretKey: SMTP_PORT
      remoteRef:
        key: apps/theater-vaultwarden
        property: SMTP_PORT
    - secretKey: SMTP_FROM
      remoteRef:
        key: apps/theater-vaultwarden
        property: SMTP_FROM
    - secretKey: SMTP_FROM_NAME
      remoteRef:
        key: apps/theater-vaultwarden
        property: SMTP_FROM_NAME
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: apps/theater-vaultwarden
        property: SMTP_USERNAME
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: apps/theater-vaultwarden
        property: SMTP_PASSWORD
    - secretKey: SMTP_AUTH_MECHANISM
      remoteRef:
        key: apps/theater-vaultwarden
        property: SMTP_AUTH_MECHANISM
