apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: theater-vaultwarden
resources:
  - namespace.yaml
  - sa-secrets.yaml
  - secretstore.yaml
  - externalsecret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingressroute.yaml

replacements:
  - source:
      kind: Certificate
      name: theater-vaultwarden-tls
      fieldPath: spec.dnsNames.0
    targets:
      - select:
          kind: IngressRoute
          name: theater-vaultwarden
        fieldPaths:
          - spec.routes.0.match
        options:
          delimiter: "`"
          index: 1

