apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: theater-vaultwarden
resources:
  - namespace.yaml
  - sa-secrets.yaml
  - secretstore.yaml
  - externalsecret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingressroute.yaml
