apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: theater-vaultwarden-data
  namespace: theater-vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-ha
