apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: theater-vaultwarden-vault
  namespace: theater-vaultwarden
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "theater-vaultwarden-eso"
          serviceAccountRef:
            name: theater-vaultwarden-secrets
